
export const createTemplateProps = (DATA, TIMINGS) => ({
	DATA: DATA.DATA,
	VIDEOMETA: DATA.VIDEOMETA,
	TIMINGS: DATA.TIMINGS,
	FPS_MAIN: TIMINGS.FPS_MAIN,
	FPS_SCORECARD: TIMINGS.FPS_SCORECARD,
	FPS_LADDER: TIMINGS.FPS_LADDER,
	TemplateVariation: DATA.VIDEOMETA.Video.TemplateVariation,
});